#!/usr/bin/env python3
"""Build Leave & Attendance Pydantic schemas."""
import os

base = os.path.dirname(os.path.abspath(__file__))

def write_file(rel_path, content):
    full = os.path.join(base, rel_path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(content)
    print(f"  wrote {rel_path}")

# 1. department schemas

write_file("backend/app/schemas/department.py", '"""Pydantic schemas for department resources."""\n'
'\n'
'from datetime import datetime\n'
'from typing import Optional\n'
'\n'
'from pydantic import BaseModel, Field\n'
'\n'
'\n'
'class DepartmentCreate(BaseModel):\n'
'    """Schema for creating a department."""\n'
'\n'
'    name: str = Field(..., min_length=1, max_length=100)\n'
'    description: Optional[str] = None\n'
'    manager_id: Optional[int] = None\n'
'\n'
'\n'
'class DepartmentUpdate(BaseModel):\n'
'    """Schema for updating a department."""\n'
'\n'
'    name: Optional[str] = Field(None, min_length=1, max_length=100)\n'
'    description: Optional[str] = None\n'
'    manager_id: Optional[int] = None\n'
'\n'
'\n'
'class DepartmentOut(BaseModel):\n'
'    """Department response schema."""\n'
'\n'
'    id: int\n'
'    name: str\n'
'    description: str | None\n'
'    manager_id: int | None\n'
'    created_at: datetime\n'
'    updated_at: datetime\n'
'\n'
'    model_config = {"from_attributes": True}\n'
)

# 2. leave_type schemas

write_file("backend/app/schemas/leave_type.py", '"""Pydantic schemas for leave type resources."""\n'
'\n'
'from datetime import datetime\n'
'from typing import Optional\n'
'\n'
'from pydantic import BaseModel, Field\n'
'\n'
'\n'
'class LeaveTypeCreate(BaseModel):\n'
'    """Schema for creating a leave type."""\n'
'\n'
'    name: str = Field(..., min_length=1, max_length=50)\n'
'    description: Optional[str] = Field(None, max_length=255)\n'
'    days_per_year: Optional[float] = Field(default=25.0, ge=0, le=365)\n'
'    max_consecutive_days: Optional[int] = Field(default=5, ge=1, le=365)\n'
'    is_paid: Optional[bool] = True\n'
'    color: Optional[str] = Field(default="#3b82f6", pattern="^#[0-9a-fA-F]{6}$")\n'
'    requires_approval: Optional[bool] = True\n'
'    active: Optional[bool] = True\n'
'\n'
'\n'
'class LeaveTypeUpdate(BaseModel):\n'
'    """Schema for updating a leave type."""\n'
'\n'
'    name: Optional[str] = Field(None, min_length=1, max_length=50)\n'
'    description: Optional[str] = Field(None, max_length=255)\n'
'    days_per_year: Optional[float] = Field(None, ge=0, le=365)\n'
'    max_consecutive_days: Optional[int] = Field(None, ge=1, le=365)\n'
'    is_paid: Optional[bool] = None\n'
'    color: Optional[str] = Field(None, pattern="^#[0-9a-fA-F]{6}$")\n'
'    requires_approval: Optional[bool] = None\n'
'    active: Optional[bool] = None\n'
'\n'
'\n'
'class LeaveTypeOut(BaseModel):\n'
'    """Leave type response schema."""\n'
'\n'
'    id: int\n'
'    name: str\n'
'    description: str | None\n'
'    days_per_year: float\n'
'    max_consecutive_days: int\n'
'    is_paid: bool\n'
'    color: str\n'
'    requires_approval: bool\n'
'    active: bool\n'
'    created_at: datetime\n'
'\n'
'    model_config = {"from_attributes": True}\n'
)

# 3. leave_balance schemas

write_file("backend/app/schemas/leave_balance.py", '"""Pydantic schemas for leave balance resources."""\n'
'\n'
'from datetime import datetime\n'
'\n'
'from pydantic import BaseModel, Field\n'
'\n'
'\n'
'class LeaveBalanceOut(BaseModel):\n'
'    """Leave balance response schema."""\n'
'\n'
'    id: int\n'
'    employee_id: int\n'
'    leave_type_id: int\n'
'    leave_type_name: str\n'
'    year: int\n'
'    allocated: float\n'
'    used: float\n'
'    carried_over: float\n'
'    remaining: float\n'
'    utilization_pct: float\n'
'    created_at: datetime\n'
'    updated_at: datetime\n'
'\n'
'    model_config = {"from_attributes": True}\n'
'\n'
'\n'
'class LeaveBalanceCreate(BaseModel):\n'
'    """Schema for creating an initial leave balance."""\n'
'\n'
'    employee_id: int = Field(..., ge=1)\n'
'    leave_type_id: int = Field(..., ge=1)\n'
'    year: int = Field(..., ge=2000, le=2100)\n'
'    allocated: float = Field(..., ge=0, le=365)\n'
'    carried_over: float = Field(default=0.0, ge=0, le=365)\n'
)

# 4. leave_request schemas

write_file("backend/app/schemas/leave_request.py", '"""Pydantic schemas for leave request resources."""\n'
'\n'
'from datetime import date, datetime\n'
'from typing import Optional\n'
'\n'
'from pydantic import BaseModel, Field\n'
'\n'
'\n'
'class LeaveRequestCreate(BaseModel):\n'
'    """Schema for creating a leave request."""\n'
'\n'
'    leave_type_id: int = Field(..., ge=1)\n'
'    start_date: date\n'
'    end_date: date\n'
'    reason: Optional[str] = Field(None, max_length=500)\n'
'\n'
'\n'
'class LeaveRequestUpdate(BaseModel):\n'
'    """Schema for approving or rejecting a leave request."""\n'
'\n'
'    status: str = Field(..., pattern="^(approved|rejected)$")\n'
'    manager_note: Optional[str] = None\n'
'\n'
'\n'
'class LeaveRequestOut(BaseModel):\n'
'    """Leave request response schema."""\n'
'\n'
'    id: int\n'
'    employee_id: int\n'
'    employee_name: str\n'
'    employee_avatar_url: str | None\n'
'    leave_type_id: int\n'
'    leave_type_name: str\n'
'    leave_type_color: str\n'
'    leave_type_is_paid: bool\n'
'    department_id: int | None\n'
'    department_name: str | None\n'
'    start_date: date\n'
'    end_date: date\n'
'    days_requested: float\n'
'    status: str\n'
'    reason: str | None\n'
'    approved_by: int | None\n'
'    approver_name: str | None\n'
'    manager_note: str | None\n'
'    created_at: datetime\n'
'    updated_at: datetime\n'
'\n'
'    model_config = {"from_attributes": True}\n'
'\n'
'\n'
'class LeaveRequestListParams(BaseModel):\n'
'    """Query parameters for listing leave requests."""\n'
'\n'
'    page: int = Field(default=1, ge=1)\n'
'    page_size: int = Field(default=20, ge=1, le=100)\n'
'    status: Optional[str] = None  # pending | approved | rejected\n'
'    leave_type_id: Optional[int] = None\n'
'\n'
'\n'
'class PaginatedLeaveResponse(BaseModel):\n'
'    """Wrapper for paginated leave request responses."""\n'
'\n'
'    items: list[LeaveRequestOut]\n'
'    total: int\n'
'    page: int\n'
'    page_size: int\n'
'    total_pages: int\n'
)

# 5. Update schemas/__init__.py

write_file("backend/app/schemas/__init__.py", '# Pydantic schemas live in dedicated files per model\n')

print("\n--- Schemas complete ---")